config/routes.rb
Rails.application.routes.draw do
  resources :specialties

  root 'bars#index'

  resources :bars, only: [:index, :show]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  belongs_to :bar


  def self.ransackable_attributes(auth_object = nil)
    ["bar_id", "category", "created_at", "description", "id", "id_value", "is_main", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["bar"]
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: %i[ show edit update destroy ]

  # GET /specialties
  def index
    @specialties = Specialty.all
  end

  # GET /specialties/1
  def show
  end

  # GET /specialties/new
  def new
    @specialty = Specialty.new
  end

  # GET /specialties/1/edit
  def edit
  end

  # POST /specialties
  def create
    @specialty = Specialty.new(specialty_params)

    if @specialty.save
      redirect_to @specialty, notice: "Specialty was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /specialties/1
  def update
    if @specialty.update(specialty_params)
      redirect_to @specialty, notice: "Specialty was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /specialties/1
  def destroy
    @specialty.destroy!
    redirect_to specialties_url, notice: "Specialty was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialty
      @specialty = Specialty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialty_params
      params.require(:specialty).permit(:bar_id, :category, :is_main, :description)
    end
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/specialties/_form.html.erb
<%= form_with(model: specialty, class: "contents") do |form| %>
  <% if specialty.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul class="list-disc ml-6">
        <% specialty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :bar_id %>
    <%= form.text_field :bar_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": specialty.errors[:bar_id].none?, "border-red-400 focus:outline-red-600": specialty.errors[:bar_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": specialty.errors[:category].none?, "border-red-400 focus:outline-red-600": specialty.errors[:category].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :is_main %>
    <%= form.check_box :is_main, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": specialty.errors[:is_main].none?, "border-red-400 focus:outline-red-600": specialty.errors[:is_main].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": specialty.errors[:description].none?, "border-red-400 focus:outline-red-600": specialty.errors[:description].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/specialties/_specialty.html.erb
<div id="<%= dom_id specialty %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Bar:</strong>
    <%= specialty.bar_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Category:</strong>
    <%= specialty.category %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Is main:</strong>
    <%= specialty.is_main? ? "Yes" : "No" %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= specialty.description %>
  </div>
</div>

app/views/specialties/edit.html.erb
<% content_for :title, "Editing specialty" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing specialty</h1>

  <%= render "form", specialty: @specialty %>

  <%= link_to "Show this specialty", @specialty, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to specialties", specialties_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/specialties/index.html.erb
<% content_for :title, "Specialties" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Specialties</h1>
    <%= link_to "New specialty", new_specialty_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="specialties" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @specialties.any? %>
      <% @specialties.each do |specialty| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render specialty %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", specialty, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_specialty_path(specialty), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", specialty, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No specialties found.</p>
    <% end %>
  </div>
</div>

app/views/specialties/new.html.erb
<% content_for :title, "New specialty" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New specialty</h1>

  <%= render "form", specialty: @specialty %>

  <%= link_to "Back to specialties", specialties_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/specialties/show.html.erb
<% content_for :title, "Showing specialty" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing specialty</h1>

  <%= render @specialty %>

  <%= link_to "Edit this specialty", edit_specialty_path(@specialty), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to specialties", specialties_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this specialty", @specialty, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>